version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
      - image: selenium/standalone-chrome:3.141

    steps:
      - checkout

      - run:
          name: Install requests
          command: |
            sudo pip install -r requirement.txt
            sudo pip install chromedriver

      - run:
          name: Run Selenium test
          command: |
            python -m pytest testcases/test_index.py

      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file